In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
%matplotlib inline

In [4]:
from sklearn.datasets import load_breast_cancer

In [5]:
l = load_breast_cancer()

In [9]:
l.keys()


dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [11]:
l['data']

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [12]:
df_cancer = pd.DataFrame(np.c_[l['data'], l['target']], columns = np.append(l['feature_names'], ['target']))


In [13]:
df_cancer.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890     0.0  
1          0.2750                  0.08902     0.0  
2          0.3613                  0.08758     0.0  
3          0.6638                  0.17300     0.0  
4          0.2364                  0.07678     0.0  

[5 rows x 31 columns]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X = df_cancer.drop('target',axis=1)

y= df_cancer['target']

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler = StandardScaler()

In [22]:
X_train.head(2)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
47         13.17         18.66           85.98      534.6          0.11580   
527        12.34         12.27           78.94      468.5          0.09003   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
47            0.12310         0.12260              0.07340         0.2128   
527           0.06307         0.02958              0.02647         0.1689   

     mean fractal dimension  ...  worst radius  worst texture  \
47                  0.06777  ...         15.67          27.95   
527                 0.05808  ...         13.61          19.27   

     worst perimeter  worst area  worst smoothness  worst compactness  \
47            102.80       759.4            0.1786             0.4166   
527            87.22       564.9            0.1292             0.2074   

     worst concavity  worst concave points  worst symmetry  \
47            0.5006                0.2088           0.390   
527           0.1791                0.1070           0.311   

     worst fractal dimension  
47                   0.11790  
527                  0.07592  

[2 rows x 30 columns]

In [23]:
X_train = scaler.fit_transform(X_train)

In [25]:
X_train

array([[-0.28070029, -0.10714079, -0.2516669 , ...,  1.45474568,
         1.67340157,  1.92775575],
       [-0.52464302, -1.62540348, -0.55199551, ..., -0.10332565,
         0.363454  , -0.41885018],
       [-0.0426357 ,  0.12095501, -0.0323929 , ...,  1.05527945,
         0.47786714,  1.23461822],
       ...,
       [ 1.11241842,  0.45359472,  1.38734231, ...,  1.26496096,
         0.5873058 ,  2.0339623 ],
       [ 0.48639672,  0.90265834,  0.58959446, ...,  1.37209749,
         0.63539248,  2.33581252],
       [-1.24882962, -0.43740451, -1.23541371, ..., -0.88572846,
         0.16281646, -0.53735434]])

In [26]:
X_test.head(2)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
28         15.30         25.27          102.40      732.4           0.1082   
163        12.34         22.22           79.85      464.5           0.1012   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
28             0.1697          0.1683              0.08751         0.1926   
163            0.1015          0.0537              0.02822         0.1551   

     mean fractal dimension  ...  worst radius  worst texture  \
28                  0.06540  ...         20.27          36.71   
163                 0.06761  ...         13.58          28.68   

     worst perimeter  worst area  worst smoothness  worst compactness  \
28            149.30      1269.0            0.1641             0.6110   
163            87.36       553.0            0.1452             0.2338   

     worst concavity  worst concave points  worst symmetry  \
28            0.6335               0.20240          0.4027   
163           0.1688               0.08194          0.2268   

     worst fractal dimension  
28                   0.09876  
163                  0.09082  

[2 rows x 30 columns]

In [27]:
X_test = scaler.transform(X_test)

In [28]:
from sklearn.svm import SVC

In [29]:
svc = SVC()

In [30]:
svc.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [31]:
pre= svc.predict(X_test)

In [32]:
from sklearn.metrics import confusion_matrix,classification_report

In [33]:
print(classification_report(y_test,pre))

              precision    recall  f1-score   support

         0.0       0.98      0.97      0.98        61
         1.0       0.98      0.99      0.99       110

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171



In [35]:
cm = confusion_matrix(y_test,pre)

In [49]:
print(cm)

[[ 59   2]
 [  1 109]]


In [50]:
from sklearn.model_selection import cross_val_score

In [91]:
from sklearn.model_selection import GridSearchCV

In [92]:
paramaters = [{'C':[10,12,11,9],'gamma':[0.05,0.01,0.1,0.12],'kernel':['rbf']}]
grid = GridSearchCV(estimator=SVC(),param_grid=paramaters,verbose=3,refit=True,cv=10)

In [93]:
grid.fit(X_train,y_train)

Fitting 10 folds for each of 16 candidates, totalling 160 fits
[CV] C=10, gamma=0.05, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.05, kernel=rbf, score=1.000, total=   0.0s
[CV] C=10, gamma=0.05, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.05, kernel=rbf, score=0.950, total=   0.0s
[CV] C=10, gamma=0.05, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.05, kernel=rbf, score=0.975, total=   0.0s
[CV] C=10, gamma=0.05, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.05, kernel=rbf, score=0.875, total=   0.0s
[CV] C=10, gamma=0.05, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.05, kernel=rbf, score=0.975, total=   0.0s
[CV] C=10, gamma=0.05, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.05, kernel=rbf, score=0.925, total=   0.0s
[CV] C=10, gamma=0.05, kernel=rbf ....................................
[CV] ........ 

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.976, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.950, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.975, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.900, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.925, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.925, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.975, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] .

[CV] ........ C=11, gamma=0.01, kernel=rbf, score=1.000, total=   0.0s
[CV] C=11, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=11, gamma=0.01, kernel=rbf, score=0.975, total=   0.0s
[CV] C=11, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=11, gamma=0.01, kernel=rbf, score=0.950, total=   0.0s
[CV] C=11, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=11, gamma=0.01, kernel=rbf, score=0.950, total=   0.0s
[CV] C=11, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=11, gamma=0.01, kernel=rbf, score=1.000, total=   0.0s
[CV] C=11, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=11, gamma=0.01, kernel=rbf, score=0.950, total=   0.0s
[CV] C=11, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=11, gamma=0.01, kernel=rbf, score=1.000, total=   0.0s
[CV] C=11, gamma=0.01, kernel=rbf ....................................
[CV] .

[CV] ......... C=9, gamma=0.12, kernel=rbf, score=0.900, total=   0.0s
[CV] C=9, gamma=0.12, kernel=rbf .....................................
[CV] ......... C=9, gamma=0.12, kernel=rbf, score=0.925, total=   0.0s
[CV] C=9, gamma=0.12, kernel=rbf .....................................
[CV] ......... C=9, gamma=0.12, kernel=rbf, score=0.925, total=   0.1s
[CV] C=9, gamma=0.12, kernel=rbf .....................................
[CV] ......... C=9, gamma=0.12, kernel=rbf, score=0.975, total=   0.0s
[CV] C=9, gamma=0.12, kernel=rbf .....................................
[CV] ......... C=9, gamma=0.12, kernel=rbf, score=0.974, total=   0.0s
[CV] C=9, gamma=0.12, kernel=rbf .....................................
[CV] ......... C=9, gamma=0.12, kernel=rbf, score=0.949, total=   0.0s
[CV] C=9, gamma=0.12, kernel=rbf .....................................
[CV] ......... C=9, gamma=0.12, kernel=rbf, score=0.897, total=   0.0s


[Parallel(n_jobs=1)]: Done 160 out of 160 | elapsed:    1.4s finished


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid=[{'C': [10, 12, 11, 9],
                          'gamma': [0.05, 0.01, 0.1, 0.12],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [94]:
grid.best_params_

{'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}

In [95]:
grid.best_score_

0.9773869346733668

In [96]:
pr=grid.predict(X_test)

In [97]:
print(confusion_matrix(y_test,pr))

[[ 59   2]
 [  1 109]]


In [98]:
print(classification_report(y_test,pr))

              precision    recall  f1-score   support

         0.0       0.98      0.97      0.98        61
         1.0       0.98      0.99      0.99       110

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171

